type PageProps = {
  params: {
    blogId: string;
  };
  searchParams?: {
    [key: string]: string | string[] | undefined;
  };
};

export async function generateMetadata({ params }: PageProps) {
  const { blogId } = await params;

  return {
    title: `Blog ${blogId}`,
    description: `Blog page for post ${blogId}`,
  };
}

// dynamic params
// use it when we want that it does not create the new dynamic page as if we have 200 pages that are
// static site generated and we want that no more page generatd at run time and served so use this
export const dynamicParams = false; // now no page will be generated by ssg at fly only the pages we have at the build time

// ------ ISR ------
// when wa want to update the content that is dynamic and changing and we want that update it and regenerate the static html page
export const revalidate = 300;

// Static Site Generation
// generate the dynamic page at the buid time and also as user go on the pages and at run time create the html at run time and generate the html as well

interface Todo {
  id: number;
  userId: number;
  title: string;
  completed: boolean;
}

export async function generateStaticParams() {
  const response = await fetch("https://jsonplaceholder.typicode.com/todos");

  const data: Todo[] = await response.json();

  return data.map((item) => ({
    blogId: item.id.toString(),
  }));
}

export default async function Blog({ params }: PageProps) {
  const { blogId } = await params;
  console.log("blogId", blogId);

  // error handling in the next js in server component
  // if (blogId % 2 === 0) {
  //   // console.log(object);
  //   throw new Error("blog can be only the odd number ");
  // }

  return (
    <>
      <div>
        <h1 className="text-3xl">Welcome to Our Blog {blogId}</h1>
        <p>This is blog {blogId} page.</p>
        <p>Data : {new Date().toLocaleString()}</p>
      </div>
    </>
  );
}
